
//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

namespace BansheeGz.BGSpline.Editor
{
	public static class BGBinaryResources
	{
		public static readonly BGEditorIcon BGAdd123 = new BGEditorIcon(0,1024,16,16);
		public static readonly BGEditorIcon BGBoxWhite123 = new BGEditorIcon(1024,1024,16,16);
		public static readonly BGEditorIcon BGBoxWithBorder123 = new BGEditorIcon(2048,4096,32,32);
		public static readonly BGEditorIcon BGCcCollider2DBox123 = new BGEditorIcon(6144,65536,128,128);
		public static readonly BGEditorIcon BGCcCollider2DEdge123 = new BGEditorIcon(71680,65536,128,128);
		public static readonly BGEditorIcon BGCcCollider3DBox123 = new BGEditorIcon(137216,65536,128,128);
		public static readonly BGEditorIcon BGCcColliderCapsule123 = new BGEditorIcon(202752,65536,128,128);
		public static readonly BGEditorIcon BGCcCursor123 = new BGEditorIcon(268288,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorChangeLinear123 = new BGEditorIcon(284672,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectRotate123 = new BGEditorIcon(301056,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectScale123 = new BGEditorIcon(317440,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectTranslate123 = new BGEditorIcon(333824,16384,64,64);
		public static readonly BGEditorIcon BGCcEditName123 = new BGEditorIcon(350208,1024,16,16);
		public static readonly BGEditorIcon BGCcMath123 = new BGEditorIcon(351232,16384,64,64);
		public static readonly BGEditorIcon BGCcNoImage123 = new BGEditorIcon(367616,65536,128,128);
		public static readonly BGEditorIcon BGCcSplitterPolyline123 = new BGEditorIcon(433152,16384,64,64);
		public static readonly BGEditorIcon BGCcSweep2d123 = new BGEditorIcon(449536,16384,64,64);
		public static readonly BGEditorIcon BGCcTriangulate2D123 = new BGEditorIcon(465920,16384,64,64);
		public static readonly BGEditorIcon BGCcTrs123 = new BGEditorIcon(482304,16384,64,64);
		public static readonly BGEditorIcon BGCcVisualizationLineRenderer123 = new BGEditorIcon(498688,16384,64,64);
		public static readonly BGEditorIcon BGCollapseAll123 = new BGEditorIcon(515072,1024,16,16);
		public static readonly BGEditorIcon BGCollapsed123 = new BGEditorIcon(516096,1024,16,16);
		public static readonly BGEditorIcon BGComponents123 = new BGEditorIcon(517120,2720,68,10);
		public static readonly BGEditorIcon BGControlAbsent123 = new BGEditorIcon(519840,4096,32,32);
		public static readonly BGEditorIcon BGControlBezierIndependent123 = new BGEditorIcon(523936,4096,32,32);
		public static readonly BGEditorIcon BGControlBezierSymmetrical123 = new BGEditorIcon(528032,4096,32,32);
		public static readonly BGEditorIcon BGConvertAll123 = new BGEditorIcon(532128,2816,44,16);
		public static readonly BGEditorIcon BGCopy123 = new BGEditorIcon(534944,1024,16,16);
		public static readonly BGEditorIcon BGCurveComponents123 = new BGEditorIcon(535968,34560,360,24);
		public static readonly BGEditorIcon BGCurveLogo123 = new BGEditorIcon(570528,38016,396,24);
		public static readonly BGEditorIcon BGDelete123 = new BGEditorIcon(608544,1024,16,16);
		public static readonly BGEditorIcon BGDeSelectAll123 = new BGEditorIcon(609568,2240,35,16);
		public static readonly BGEditorIcon BGExpandAll123 = new BGEditorIcon(611808,1024,16,16);
		public static readonly BGEditorIcon BGExpanded123 = new BGEditorIcon(612832,1024,16,16);
		public static readonly BGEditorIcon BGFields123 = new BGEditorIcon(613856,992,31,8);
		public static readonly BGEditorIcon BGHandlesOff123 = new BGEditorIcon(614848,1024,16,16);
		public static readonly BGEditorIcon BGHandlesOn123 = new BGEditorIcon(615872,1024,16,16);
		public static readonly BGEditorIcon BGHelp123 = new BGEditorIcon(616896,1024,16,16);
		public static readonly BGEditorIcon BGHiddenOff123 = new BGEditorIcon(617920,1024,16,16);
		public static readonly BGEditorIcon BGHiddenOn123 = new BGEditorIcon(618944,1024,16,16);
		public static readonly BGEditorIcon BGLockOff123 = new BGEditorIcon(619968,4096,32,32);
		public static readonly BGEditorIcon BGLockOn123 = new BGEditorIcon(624064,4096,32,32);
		public static readonly BGEditorIcon BGMenuItemBackground123 = new BGEditorIcon(628160,4096,32,32);
		public static readonly BGEditorIcon BGMoveDown123 = new BGEditorIcon(632256,1024,16,16);
		public static readonly BGEditorIcon BGMoveUp123 = new BGEditorIcon(633280,1024,16,16);
		public static readonly BGEditorIcon BGOff123 = new BGEditorIcon(634304,1024,16,16);
		public static readonly BGEditorIcon BGOn123 = new BGEditorIcon(635328,1024,16,16);
		public static readonly BGEditorIcon BGPaste123 = new BGEditorIcon(636352,1024,16,16);
		public static readonly BGEditorIcon BGPointDelete123 = new BGEditorIcon(637376,4096,32,32);
		public static readonly BGEditorIcon BGPointInsertAfter123 = new BGEditorIcon(641472,4096,32,32);
		public static readonly BGEditorIcon BGPointInsertBefore123 = new BGEditorIcon(645568,4096,32,32);
		public static readonly BGEditorIcon BGPoints123 = new BGEditorIcon(649664,1056,33,8);
		public static readonly BGEditorIcon BGPointSelected123 = new BGEditorIcon(650720,4096,32,32);
		public static readonly BGEditorIcon BGSelectAll123 = new BGEditorIcon(654816,2240,35,16);
		public static readonly BGEditorIcon BGSelectionAdd123 = new BGEditorIcon(657056,4096,32,32);
		public static readonly BGEditorIcon BGSelectionRemove123 = new BGEditorIcon(661152,4096,32,32);
		public static readonly BGEditorIcon BGSettings123 = new BGEditorIcon(665248,1720,43,10);
		public static readonly BGEditorIcon BGSettingsIcon123 = new BGEditorIcon(666968,4096,32,32);
		public static readonly BGEditorIcon BGTableCellDark123 = new BGEditorIcon(671064,2312,34,17);
		public static readonly BGEditorIcon BGTableCellLight123 = new BGEditorIcon(673376,2312,34,17);
		public static readonly BGEditorIcon BGTableHeaderDark123 = new BGEditorIcon(675688,2312,34,17);
		public static readonly BGEditorIcon BGTableHeaderLight123 = new BGEditorIcon(678000,2312,34,17);
		public static readonly BGEditorIcon BGTableTitleDark123 = new BGEditorIcon(680312,2312,34,17);
		public static readonly BGEditorIcon BGTableTitleLight123 = new BGEditorIcon(682624,2312,34,17);
		public static readonly BGEditorIcon BGTickNo123 = new BGEditorIcon(684936,2304,24,24);
		public static readonly BGEditorIcon BGTickYes123 = new BGEditorIcon(687240,2304,24,24);
	}
}
