
//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

namespace BansheeGz.BGSpline.Editor
{
	public static class BGBinaryResources
	{
		public static readonly BGEditorIcon BGAdd123 = new BGEditorIcon(0,1024,16,16);
		public static readonly BGEditorIcon BGBoxWhite123 = new BGEditorIcon(1024,1024,16,16);
		public static readonly BGEditorIcon BGBoxWithBorder123 = new BGEditorIcon(2048,4096,32,32);
		public static readonly BGEditorIcon BGCcCollider2DBox123 = new BGEditorIcon(6144,65536,128,128);
		public static readonly BGEditorIcon BGCcCollider2DEdge123 = new BGEditorIcon(71680,65536,128,128);
		public static readonly BGEditorIcon BGCcCollider3DBox123 = new BGEditorIcon(137216,65536,128,128);
		public static readonly BGEditorIcon BGCcCursor123 = new BGEditorIcon(202752,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorChangeLinear123 = new BGEditorIcon(219136,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectRotate123 = new BGEditorIcon(235520,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectScale123 = new BGEditorIcon(251904,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectTranslate123 = new BGEditorIcon(268288,16384,64,64);
		public static readonly BGEditorIcon BGCcEditName123 = new BGEditorIcon(284672,1024,16,16);
		public static readonly BGEditorIcon BGCcMath123 = new BGEditorIcon(285696,16384,64,64);
		public static readonly BGEditorIcon BGCcNoImage123 = new BGEditorIcon(302080,65536,128,128);
		public static readonly BGEditorIcon BGCcSplitterPolyline123 = new BGEditorIcon(367616,16384,64,64);
		public static readonly BGEditorIcon BGCcSweep2d123 = new BGEditorIcon(384000,16384,64,64);
		public static readonly BGEditorIcon BGCcTriangulate2D123 = new BGEditorIcon(400384,16384,64,64);
		public static readonly BGEditorIcon BGCcTrs123 = new BGEditorIcon(416768,16384,64,64);
		public static readonly BGEditorIcon BGCcVisualizationLineRenderer123 = new BGEditorIcon(433152,16384,64,64);
		public static readonly BGEditorIcon BGCollapseAll123 = new BGEditorIcon(449536,1024,16,16);
		public static readonly BGEditorIcon BGCollapsed123 = new BGEditorIcon(450560,1024,16,16);
		public static readonly BGEditorIcon BGComponents123 = new BGEditorIcon(451584,2720,68,10);
		public static readonly BGEditorIcon BGControlAbsent123 = new BGEditorIcon(454304,4096,32,32);
		public static readonly BGEditorIcon BGControlBezierIndependent123 = new BGEditorIcon(458400,4096,32,32);
		public static readonly BGEditorIcon BGControlBezierSymmetrical123 = new BGEditorIcon(462496,4096,32,32);
		public static readonly BGEditorIcon BGConvertAll123 = new BGEditorIcon(466592,2816,44,16);
		public static readonly BGEditorIcon BGCopy123 = new BGEditorIcon(469408,1024,16,16);
		public static readonly BGEditorIcon BGCurveComponents123 = new BGEditorIcon(470432,34560,360,24);
		public static readonly BGEditorIcon BGCurveLogo123 = new BGEditorIcon(504992,38016,396,24);
		public static readonly BGEditorIcon BGDelete123 = new BGEditorIcon(543008,1024,16,16);
		public static readonly BGEditorIcon BGDeSelectAll123 = new BGEditorIcon(544032,2240,35,16);
		public static readonly BGEditorIcon BGExpandAll123 = new BGEditorIcon(546272,1024,16,16);
		public static readonly BGEditorIcon BGExpanded123 = new BGEditorIcon(547296,1024,16,16);
		public static readonly BGEditorIcon BGFields123 = new BGEditorIcon(548320,992,31,8);
		public static readonly BGEditorIcon BGHandlesOff123 = new BGEditorIcon(549312,1024,16,16);
		public static readonly BGEditorIcon BGHandlesOn123 = new BGEditorIcon(550336,1024,16,16);
		public static readonly BGEditorIcon BGHelp123 = new BGEditorIcon(551360,1024,16,16);
		public static readonly BGEditorIcon BGHiddenOff123 = new BGEditorIcon(552384,1024,16,16);
		public static readonly BGEditorIcon BGHiddenOn123 = new BGEditorIcon(553408,1024,16,16);
		public static readonly BGEditorIcon BGLockOff123 = new BGEditorIcon(554432,4096,32,32);
		public static readonly BGEditorIcon BGLockOn123 = new BGEditorIcon(558528,4096,32,32);
		public static readonly BGEditorIcon BGMenuItemBackground123 = new BGEditorIcon(562624,4096,32,32);
		public static readonly BGEditorIcon BGMoveDown123 = new BGEditorIcon(566720,1024,16,16);
		public static readonly BGEditorIcon BGMoveUp123 = new BGEditorIcon(567744,1024,16,16);
		public static readonly BGEditorIcon BGOff123 = new BGEditorIcon(568768,1024,16,16);
		public static readonly BGEditorIcon BGOn123 = new BGEditorIcon(569792,1024,16,16);
		public static readonly BGEditorIcon BGPaste123 = new BGEditorIcon(570816,1024,16,16);
		public static readonly BGEditorIcon BGPointDelete123 = new BGEditorIcon(571840,4096,32,32);
		public static readonly BGEditorIcon BGPointInsertAfter123 = new BGEditorIcon(575936,4096,32,32);
		public static readonly BGEditorIcon BGPointInsertBefore123 = new BGEditorIcon(580032,4096,32,32);
		public static readonly BGEditorIcon BGPoints123 = new BGEditorIcon(584128,1056,33,8);
		public static readonly BGEditorIcon BGPointSelected123 = new BGEditorIcon(585184,4096,32,32);
		public static readonly BGEditorIcon BGSelectAll123 = new BGEditorIcon(589280,2240,35,16);
		public static readonly BGEditorIcon BGSelectionAdd123 = new BGEditorIcon(591520,4096,32,32);
		public static readonly BGEditorIcon BGSelectionRemove123 = new BGEditorIcon(595616,4096,32,32);
		public static readonly BGEditorIcon BGSettings123 = new BGEditorIcon(599712,1720,43,10);
		public static readonly BGEditorIcon BGSettingsIcon123 = new BGEditorIcon(601432,4096,32,32);
		public static readonly BGEditorIcon BGTableCell123 = new BGEditorIcon(605528,4096,32,32);
		public static readonly BGEditorIcon BGTableHeader123 = new BGEditorIcon(609624,4096,32,32);
		public static readonly BGEditorIcon BGTableTitle123 = new BGEditorIcon(613720,8192,64,32);
		public static readonly BGEditorIcon BGTickNo123 = new BGEditorIcon(621912,2304,24,24);
		public static readonly BGEditorIcon BGTickYes123 = new BGEditorIcon(624216,2304,24,24);
	}
}
