
//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

namespace BansheeGz.BGSpline.Editor
{
	public static class BGBinaryResources
	{
		public static readonly BGEditorIcon BGAdd123 = new BGEditorIcon(0,1024,16,16);
		public static readonly BGEditorIcon BGBoxWhite123 = new BGEditorIcon(1024,1024,16,16);
		public static readonly BGEditorIcon BGBoxWithBorder123 = new BGEditorIcon(2048,4096,32,32);
		public static readonly BGEditorIcon BGCcCollider2DBox123 = new BGEditorIcon(6144,65536,128,128);
		public static readonly BGEditorIcon BGCcCollider2DEdge123 = new BGEditorIcon(71680,65536,128,128);
		public static readonly BGEditorIcon BGCcCollider2DMesh123 = new BGEditorIcon(137216,65536,128,128);
		public static readonly BGEditorIcon BGCcCollider3DBox123 = new BGEditorIcon(202752,65536,128,128);
		public static readonly BGEditorIcon BGCcCollider3DMesh123 = new BGEditorIcon(268288,65536,128,128);
		public static readonly BGEditorIcon BGCcColliderCapsule123 = new BGEditorIcon(333824,65536,128,128);
		public static readonly BGEditorIcon BGCcCursor123 = new BGEditorIcon(399360,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorChangeLinear123 = new BGEditorIcon(415744,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectRotate123 = new BGEditorIcon(432128,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectScale123 = new BGEditorIcon(448512,16384,64,64);
		public static readonly BGEditorIcon BGCcCursorObjectTranslate123 = new BGEditorIcon(464896,16384,64,64);
		public static readonly BGEditorIcon BGCcEditName123 = new BGEditorIcon(481280,1024,16,16);
		public static readonly BGEditorIcon BGCcMath123 = new BGEditorIcon(482304,16384,64,64);
		public static readonly BGEditorIcon BGCcNoImage123 = new BGEditorIcon(498688,65536,128,128);
		public static readonly BGEditorIcon BGCcSplitterPolyline123 = new BGEditorIcon(564224,16384,64,64);
		public static readonly BGEditorIcon BGCcSweep2d123 = new BGEditorIcon(580608,16384,64,64);
		public static readonly BGEditorIcon BGCcTriangulate2D123 = new BGEditorIcon(596992,16384,64,64);
		public static readonly BGEditorIcon BGCcTrs123 = new BGEditorIcon(613376,16384,64,64);
		public static readonly BGEditorIcon BGCcVisualizationLineRenderer123 = new BGEditorIcon(629760,16384,64,64);
		public static readonly BGEditorIcon BGCollapseAll123 = new BGEditorIcon(646144,1024,16,16);
		public static readonly BGEditorIcon BGCollapsed123 = new BGEditorIcon(647168,1024,16,16);
		public static readonly BGEditorIcon BGComponents123 = new BGEditorIcon(648192,2720,68,10);
		public static readonly BGEditorIcon BGControlAbsent123 = new BGEditorIcon(650912,4096,32,32);
		public static readonly BGEditorIcon BGControlBezierIndependent123 = new BGEditorIcon(655008,4096,32,32);
		public static readonly BGEditorIcon BGControlBezierSymmetrical123 = new BGEditorIcon(659104,4096,32,32);
		public static readonly BGEditorIcon BGConvertAll123 = new BGEditorIcon(663200,2816,44,16);
		public static readonly BGEditorIcon BGCopy123 = new BGEditorIcon(666016,1024,16,16);
		public static readonly BGEditorIcon BGCurveComponents123 = new BGEditorIcon(667040,34560,360,24);
		public static readonly BGEditorIcon BGCurveLogo123 = new BGEditorIcon(701600,38016,396,24);
		public static readonly BGEditorIcon BGDelete123 = new BGEditorIcon(739616,1024,16,16);
		public static readonly BGEditorIcon BGDeSelectAll123 = new BGEditorIcon(740640,2240,35,16);
		public static readonly BGEditorIcon BGExpandAll123 = new BGEditorIcon(742880,1024,16,16);
		public static readonly BGEditorIcon BGExpanded123 = new BGEditorIcon(743904,1024,16,16);
		public static readonly BGEditorIcon BGFields123 = new BGEditorIcon(744928,992,31,8);
		public static readonly BGEditorIcon BGHandlesOff123 = new BGEditorIcon(745920,1024,16,16);
		public static readonly BGEditorIcon BGHandlesOn123 = new BGEditorIcon(746944,1024,16,16);
		public static readonly BGEditorIcon BGHelp123 = new BGEditorIcon(747968,1024,16,16);
		public static readonly BGEditorIcon BGHiddenOff123 = new BGEditorIcon(748992,1024,16,16);
		public static readonly BGEditorIcon BGHiddenOn123 = new BGEditorIcon(750016,1024,16,16);
		public static readonly BGEditorIcon BGLockOff123 = new BGEditorIcon(751040,4096,32,32);
		public static readonly BGEditorIcon BGLockOn123 = new BGEditorIcon(755136,4096,32,32);
		public static readonly BGEditorIcon BGMenuItemBackground123 = new BGEditorIcon(759232,4096,32,32);
		public static readonly BGEditorIcon BGMoveDown123 = new BGEditorIcon(763328,1024,16,16);
		public static readonly BGEditorIcon BGMoveUp123 = new BGEditorIcon(764352,1024,16,16);
		public static readonly BGEditorIcon BGOff123 = new BGEditorIcon(765376,1024,16,16);
		public static readonly BGEditorIcon BGOn123 = new BGEditorIcon(766400,1024,16,16);
		public static readonly BGEditorIcon BGPaste123 = new BGEditorIcon(767424,1024,16,16);
		public static readonly BGEditorIcon BGPointDelete123 = new BGEditorIcon(768448,4096,32,32);
		public static readonly BGEditorIcon BGPointInsertAfter123 = new BGEditorIcon(772544,4096,32,32);
		public static readonly BGEditorIcon BGPointInsertBefore123 = new BGEditorIcon(776640,4096,32,32);
		public static readonly BGEditorIcon BGPoints123 = new BGEditorIcon(780736,1056,33,8);
		public static readonly BGEditorIcon BGPointSelected123 = new BGEditorIcon(781792,4096,32,32);
		public static readonly BGEditorIcon BGSelectAll123 = new BGEditorIcon(785888,2240,35,16);
		public static readonly BGEditorIcon BGSelectionAdd123 = new BGEditorIcon(788128,4096,32,32);
		public static readonly BGEditorIcon BGSelectionRemove123 = new BGEditorIcon(792224,4096,32,32);
		public static readonly BGEditorIcon BGSettings123 = new BGEditorIcon(796320,1720,43,10);
		public static readonly BGEditorIcon BGSettingsIcon123 = new BGEditorIcon(798040,4096,32,32);
		public static readonly BGEditorIcon BGTableCellDark123 = new BGEditorIcon(802136,2312,34,17);
		public static readonly BGEditorIcon BGTableCellLight123 = new BGEditorIcon(804448,2312,34,17);
		public static readonly BGEditorIcon BGTableHeaderDark123 = new BGEditorIcon(806760,2312,34,17);
		public static readonly BGEditorIcon BGTableHeaderLight123 = new BGEditorIcon(809072,2312,34,17);
		public static readonly BGEditorIcon BGTableTitleDark123 = new BGEditorIcon(811384,2312,34,17);
		public static readonly BGEditorIcon BGTableTitleLight123 = new BGEditorIcon(813696,2312,34,17);
		public static readonly BGEditorIcon BGTickNo123 = new BGEditorIcon(816008,2304,24,24);
		public static readonly BGEditorIcon BGTickYes123 = new BGEditorIcon(818312,2304,24,24);
	}
}
